// src/mockData.js

export const mockBooks = [
    {
        book_id: 1,
        title: "Captain Underpants and the Preposterous Plight of the Purple Potty People",
        copyright_year: 2006,
        edition: "1st",
        edition_year: 2006,
        binding: "Hardcover",
        rating: 4,
        language: "English",
        num_pages: 176,
        cover_image: "image_1.jpg",
        qty: 2
    },
    {
        book_id: 2,
        title: "Dog Man: Grime and Punishment",
        copyright_year: 2020,
        edition: "1st",
        edition_year: 2020,
        binding: "Hardcover",
        rating: 5,
        language: "English",
        num_pages: 240,
        cover_image: "image_2.jpg",
        qty: 5
    },
    {
        book_id: 3,
        title: "Smile",
        copyright_year: 2010,
        edition: "1st",
        edition_year: 2010,
        binding: "Paperback",
        rating: 5,
        language: "English",
        num_pages: 224,
        cover_image: "image_3.jpg",
        qty: 4
    },
    {
        book_id: 4,
        title: "Drama",
        copyright_year: 2012,
        edition: "1st",
        edition_year: 2012,
        binding: "Paperback",
        rating: 4,
        language: "English",
        num_pages: 240,
        cover_image: "image_4.jpg",
        qty: 3
    },
    {
        book_id: 5,
        title: "Harry Potter and the Sorcerer's Stone",
        copyright_year: 1998,
        edition: "1st",
        edition_year: 1998,
        binding: "Hardcover",
        rating: 5,
        language: "English",
        num_pages: 320,
        cover_image: "image_5.jpg",
        qty: 6
    },
    {
        book_id: 6,
        title: "Harry Potter and the Chamber of Secrets",
        copyright_year: 1999,
        edition: "1st",
        edition_year: 1999,
        binding: "Hardcover",
        rating: 5,
        language: "English",
        num_pages: 341,
        cover_image: "image_6.jpg",
        qty: 4
    },
    {
        book_id: 7,
        title: "Diary of a Wimpy Kid",
        copyright_year: 2007,
        edition: "1st",
        edition_year: 2007,
        binding: "Hardcover",
        rating: 4,
        language: "English",
        num_pages: 221,
        cover_image: "image_7.jpg",
        qty: 8
    },
    {
        book_id: 8,
        title: "Big Nate: In a Class by Himself",
        copyright_year: 2010,
        edition: "1st",
        edition_year: 2010,
        binding: "Paperback",
        rating: 4,
        language: "English",
        num_pages: 224,
        cover_image: "image_8.jpg",
        qty: 5
    },
    {
        book_id: 9,
        title: "The Lion, the Witch and the Wardrobe",
        copyright_year: 1950,
        edition: "1st",
        edition_year: 1950,
        binding: "Paperback",
        rating: 5,
        language: "English",
        num_pages: 208,
        cover_image: "image_9.jpg",
        qty: 3
    },
    {
        book_id: 10,
        title: "The Hunger Games",
        copyright_year: 2008,
        edition: "1st",
        edition_year: 2008,
        binding: "Paperback",
        rating: 5,
        language: "English",
        num_pages: 374,
        cover_image: "image_10.jpg",
        qty: 7
    }
];
