// src/mockData.js
//you might have to fix the images


export const mockBooks = [
    {
        book_id: 1,
        title: "Captain Underpants and the Preposterous Plight of the Purple Potty People",
        copyright_year: 2006,
        edition: "1st",
        edition_year: 2006,
        binding: "hardback",
        rating: 4,
        language: "English",
        num_pages: 172,
        cover_image: "image_1.jpg",
        qty: 2,
        author_name: "Pilkey, Dav",
        company_name: "Blue Sky Press",
        format: "physical",
        genre: "humor"
    },
    {
        book_id: 2,
        title: "Dog Man: Grime and Punishment",
        copyright_year: 2020,
        edition: "1st",
        edition_year: 2020,
        binding: "hardback",
        rating: 5,
        language: "English",
        num_pages: 240,
        cover_image: "image_2.jpg",
        qty: 5,
        author_name: "Pilkey, Dav",
        company_name: "Graphix",
        format: "physical",
        genre: "graphic novel"
    },
    {
        book_id: 3,
        title: "Smile",
        copyright_year: 2010,
        edition: "1st",
        edition_year: 2010,
        binding: "paperback",
        rating: 5,
        language: "English",
        num_pages: 224,
        cover_image: "image_3.jpg",
        qty: 4,
        author_name: "Telgemeier, Raina",
        company_name: "Graphix",
        format: "physical",
        genre: "graphic novel"
    },
    {
        book_id: 4,
        title: "Drama",
        copyright_year: 2012,
        edition: "1st",
        edition_year: 2012,
        binding: "paperback",
        rating: 4,
        language: "English",
        num_pages: 240,
        cover_image: "image_4.jpg",
        qty: 3,
        author_name: "Telgemeier, Raina",
        company_name: "Graphix",
        format: "physical",
        genre: "graphic novel"
    },
    {
        book_id: 5,
        title: "Harry Potter and the Sorcerer's Stone",
        copyright_year: 1998,
        edition: "1st",
        edition_year: 1998,
        binding: "hardback",
        rating: 5,
        language: "English",
        num_pages: 320,
        cover_image: "image_5.jpg",
        qty: 6,
        author_name: "Rowling, J.K",
        company_name: "Scholastic Press",
        format: "physical",
        genre: "fantasy"
    },
    {
        book_id: 6,
        title: "Harry Potter and the Chamber of Secrets",
        copyright_year: 1999,
        edition: "1st",
        edition_year: 1999,
        binding: "hardback",
        rating: 5,
        language: "English",
        num_pages: 341,
        cover_image: "image_6.jpg",
        qty: 4,
        author_name: "Rowling, J.K",
        company_name: "Scholastic Press",
        format: "physical",
        genre: "fantasy"
    },
    {
        book_id: 7,
        title: "Diary of a Wimpy Kid",
        copyright_year: 2007,
        edition: "1st",
        edition_year: 2007,
        binding: "hardback",
        rating: 4,
        language: "English",
        num_pages: 221,
        cover_image: "image_7.jpg",
        qty: 8,
        author_name: "Kinney, Jeff",
        company_name: "Amulet Books",
        format: "physical",
        genre: "humor"
    },
    {
        book_id: 8,
        title: "Big Nate: In a Class by Himself",
        copyright_year: 2010,
        edition: "1st",
        edition_year: 2010,
        binding: "paperback",
        rating: 4,
        language: "English",
        num_pages: 224,
        cover_image: "image_8.jpg",
        qty: 5,
        author_name: "Peirce, Lincoln",
        company_name: "HarperCollins",
        format: "physical",
        genre: "humor"
    },
    {
        book_id: 9,
        title: "The Lion, the Witch and the Wardrobe",
        copyright_year: 1950,
        edition: "1st",
        edition_year: 1950,
        binding: "paperback",
        rating: 5,
        language: "English",
        num_pages: 208,
        cover_image: "image_9.jpg",
        qty: 3,
        author_name: "Lewis, C.S.",
        company_name: "HarperCollins",
        format: "physical",
        genre: "fantasy"
    },
    {
        book_id: 10,
        title: "The Hunger Games",
        copyright_year: 2008,
        edition: "1st",
        edition_year: 2008,
        binding: "paperback",
        rating: 5,
        language: "English",
        num_pages: 374,
        cover_image: "image_10.jpg",
        qty: 7,
        author_name: "Collins, Suzanne",
        company_name: "Scholastic Press",
        format: "physical",
        genre: "science fiction"
    } 
];
